const audio = document.querySelector('video')
const play = document.querySelector('.play')
const stop = document.querySelector('.stop')
play.addEventListener('click',()=>{audio.play(); console.log("play")})
stop.addEventListener('click',()=>{audio.pause();console.log("stop")})
audio.addEventListener('playing', (e)=>{console.log(e.target.currentTime)})
if(audio.currentTime==1)console.log("1")
if(audio.currentTime==2)console.log("2")
if(audio.currentTime==3)console.log("3")
if(audio.currentTime==4)console.log("4")
if(audio.currentTime==5)console.log("5")
if(audio.currentTime==6)console.log("6")
